
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { String, Int, BigInt, Float, ID, Bytes, Timestamp, Boolean, Int8 } from '@sentio/sdk/store'
import { Entity, Required, One, Many, Column, ListColumn, AbstractEntity } from '@sentio/sdk/store'
import { BigDecimal } from '@sentio/bigdecimal'
import { DatabaseSchema } from '@sentio/sdk'







interface UserConstructorInput {
  id: String;
  balance: BigDecimal;
}
@Entity("User")
export class User extends AbstractEntity  {

	@Required
	@Column("String")
	id: String

	@Required
	@Column("BigDecimal")
	balance: BigDecimal
  constructor(data: UserConstructorInput) {super()}
  
}


const source = `type User @entity {
    id: String!
    balance: BigDecimal!
}
`
DatabaseSchema.register({
  source,
  entities: {
    "User": User
  }
})
